# Generated by Django 5.1.2 on 2024-10-18 18:59

import report.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('phone', models.CharField(max_length=14, verbose_name='PHONE')),
                ('email', models.CharField(max_length=254, verbose_name='EMAIL')),
                ('image', report.fields.ThumbnailImageField(upload_to='report/%Y/%m')),
                ('latitude', models.IntegerField(verbose_name='LATITUDE')),
                ('longitude', models.IntegerField(verbose_name='LONGITUDE')),
                ('date', models.DateField(auto_now_add=True, verbose_name='DATE')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
