# Generated by Django 5.1.2 on 2024-11-09 01:42

import report.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='phone',
        ),
        migrations.AddField(
            model_name='report',
            name='link_id',
            field=models.IntegerField(null=True, verbose_name='LINK_ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=report.fields.ThumbnailImageField(blank=True, null=True, upload_to='report/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LONGITUDE'),
        ),
    ]
