# Generated by Django 5.1.2 on 2024-11-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_report_email_remove_report_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='link_id',
        ),
    ]
