# Generated by Django 5.1.2 on 2024-11-20 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='priority', serialize=False, to='report.report')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('lane_count', models.IntegerField(blank=True, null=True)),
                ('average_speed', models.FloatField(blank=True, null=True)),
                ('passenger_car_traffic', models.IntegerField(blank=True, null=True)),
                ('bus_traffic', models.IntegerField(blank=True, null=True)),
                ('truck_traffic', models.IntegerField(blank=True, null=True)),
                ('traffic', models.IntegerField(blank=True, null=True)),
                ('is_frozen', models.IntegerField(blank=True, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('priority', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
