# Generated by Django 5.1.2 on 2024-11-12 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0003_remove_report_link_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='priority', serialize=False, to='report.report')),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('traffic', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
