# Generated by Django 5.1.2 on 2024-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
