# Generated by Django 5.1.2 on 2024-11-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_priority_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ('-priority', 'date')},
        ),
    ]
