# Generated by Django 5.1.2 on 2024-11-16 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_priority_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ('priority', 'date')},
        ),
        migrations.AddField(
            model_name='priority',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 16, 15, 50, 28, 745486)),
            preserve_default=False,
        ),
    ]
