# Generated by Django 5.1.2 on 2024-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_priority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
